apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-file-dir
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: "vote"
  file:
    matchDirectories:
    - dir: /etc/
      recursive: true
  action:
    Block