apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-net-icmp-audit
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  network:
    matchProtocols:
    - protocol: icmp
  action:
    Audit