apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: net-icmp-audit
spec:
  severity: 8
  selector:
    matchLabels:
      kubearmor.io/container.name: "vote"
  network:
    matchProtocols:
    - protocol: icmp
  action:
    Audit